import "@/styles/globals.css";

import { Header } from "@/components/header";

export const metadata = {
    title: "CatGround",
    description: "Generated by create next app"
};

const RootLayout = ({ children }) => {
    return (
        <html lang="en">
            <body className="dark">
                <Header />
                {children}
            </body>
        </html>
    );
}

export default RootLayout;