import "@/styles/globals.css";

import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata = {
    title: "CatGround",
    description: "Generated by create next app"
};

const RootLayout = ({ children }) => {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <Header />
                <main>
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}

export default RootLayout;